package org.aura.aura.cache;

import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * ADR-019: the Redis response cache key. Every ANSWER-AFFECTING input to a resolution is folded into
 * one hash so that "same question, same model, same prompt, same retrieved documents" hits and
 * anything else misses.
 *
 * <h2>Decision 4 — where the hash is taken determines what can invalidate you</h2>
 * Through Day 13 this key was computed BEFORE anything was retrieved, because there was nothing to
 * retrieve: the knowledge base was three hardcoded entries compiled into the jar, so its content was
 * already covered by the system-prompt bytes. Day 14 moved the knowledge into a database that people
 * edit, which breaks that coverage completely — a corrected refund window in {@code kb/} and a
 * re-ingest would change every answer the system should give, while every input to the old key stayed
 * byte-identical. The stale answer would keep being served for the full 24h TTL, confidently, with a
 * citation attached.
 *
 * <p>So the key is now computed AFTER retrieval and folds in the rendered context block. The
 * consequence is the good kind of surgical: editing one KB document changes the bytes retrieved for
 * the tickets that document answers, which changes the key for exactly those tickets, which orphans
 * exactly those entries. No TTL shortening, no clock, no manual flush, and — importantly — no
 * collateral invalidation of the tickets that document has nothing to do with.
 *
 * <h2>What is deliberately NOT in the key</h2>
 * <ul>
 *   <li><b>Chunk ids alone.</b> An id is a name, not content. Key on ids and an in-place edit to a
 *       chunk's text — the single most likely KB change there is — sails straight through, because
 *       the id it is stored under did not move. The rendered block carries the content BYTES, which
 *       is what makes the invalidation real. (The ids ride along inside those bytes as citation
 *       attributes, which is correct: they are shown to the model, so they are part of the request.)</li>
 *   <li><b>Embedding floats.</b> Never. Two embeddings of one sentence differ in low decimal places
 *       from call to call, so any float derived from a vector is effectively a nonce: a key built on
 *       one would be unique per request and the cache would report a permanent 100% miss while
 *       appearing perfectly healthy. Note the shape of the defect — not an error, not a warning, just
 *       a cost line that never comes down. That exclusion is structural rather than remembered: this
 *       method takes no vector, and the rendered block omits the distance for the same reason.</li>
 * </ul>
 */
@Component
public class CacheKeyFactory {

    /**
     * v1 → v2 (Day 14). This is not a routine bump: the key's COMPOSITION changed — a new field
     * (the context block) joined it, and the fields are now length-prefixed — so every v1 entry was
     * computed by a different function. Sharing a keyspace between two functions is how a lookup
     * quietly succeeds against a value that was never built for it.
     *
     * <p>Orphaning all pre-RAG entries is the intent, not a side effect. Every one of them holds an
     * answer produced from the three-entry hardcoded knowledge base, and none of them should be
     * served again. Old entries are not deleted — they simply become unreachable and expire on their
     * own 24h TTL.
     */
    private static final String KEY_VERSION = "v2";

    private static final String SEP = "\n--\n";

    // ADR-019 mapping note. The prompt's template says: "if classification output feeds the resolver
    // request, the classifier's model ID + rendered system prompt are answer-affecting inputs and MUST
    // be fields here too." In AURA today they are NOT: TicketController classifies and resolves
    // independently — the resolver is called on the raw ticket text, and the classification only rides
    // along in the response (see TicketController.resolve). So the classifier's model/prompt are not
    // answer-affecting inputs to the RESOLUTION and are deliberately absent from this key. The day
    // classification starts steering the resolver prompt, both MUST become fields here — otherwise every
    // entry silently serves a resolution built from a since-changed classifier.

    /**
     * @param resolverModelId       the Claude model the answer would be generated by
     * @param promptId              the prompt file's name — carried for READABILITY of the key's
     *                              composition, alongside the bytes that actually guarantee it
     * @param promptVersion         the {@code # version: N} marker parsed from that file
     * @param staticSystemPrompt    the exact text that sits before the cache_control breakpoint,
     *                              including the Day 14 grounding block
     * @param canonicalContextBlock the rendered document block, exactly as it will appear in the user
     *                              turn. It must be CANONICAL (see ContextBlockAssembler) or this key
     *                              is a hash of an arbitrary permutation and the cache never hits
     *                              twice for one logical result.
     * @param ticketText            the customer's message
     */
    public String resolutionKey(String resolverModelId,
                                String promptId,
                                int promptVersion,
                                String staticSystemPrompt,
                                String canonicalContextBlock,
                                String ticketText,
                                double temperature,
                                long maxTokens) {
        // Canonical = ONE fixed serialization. Field order and encoding are part of the contract:
        // change either and every live cache entry is silently orphaned.
        //
        // LENGTH-PREFIXED as of v2, and the upgrade is not gold-plating. v1 joined raw fields with a
        // separator and noted the theoretical aliasing gap as "not real here, we control the system
        // prompt". That premise died today. Two of these fields are no longer ours: the ticket is
        // written by a customer, and the context block is assembled from documents anyone with commit
        // access to kb/ can edit — and "\n--\n" is a markdown horizontal rule away from appearing
        // inside either. Prefixing each field with its own length makes the encoding unambiguous by
        // construction, so no arrangement of field contents can imitate a different arrangement.
        String canonical = String.join(SEP,
                lengthPrefixed(resolverModelId),
                lengthPrefixed(promptId),
                lengthPrefixed(String.valueOf(promptVersion)),
                lengthPrefixed(staticSystemPrompt),
                lengthPrefixed(canonicalContextBlock),
                lengthPrefixed(ticketText.trim()),   // trim only: whitespace is noise, but case/punctuation carry MEANING —
                lengthPrefixed(String.valueOf(temperature)),   // aggressive normalization would serve answers to slightly
                lengthPrefixed(String.valueOf(maxTokens)));    // different questions. Params are answer-affecting: raise
                                                               // maxTokens without keying it and previously-truncated
                                                               // cached answers keep serving forever.
        return "aura:resolution:" + KEY_VERSION + ":" + sha256Hex(canonical);
    }

    private static String lengthPrefixed(String field) {
        return field.length() + ":" + field;
    }

    // Hashing (vs. raw text as key) bounds key size AND keeps customer PII out of the
    // Redis keyspace — keys leak into logs and SCAN output; ticket text must not. Day 14 adds a
    // second reason of the same kind: the context block is now part of the key material, and it can
    // run to thousands of characters of policy text.
    private String sha256Hex(String input) {
        try {
            var digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(input.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is JVM-mandated; unreachable", e);
        }
    }
}
